// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoidzprqsvimgtwegowv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvaWR6cHJxc3ZpbWd0d2Vnb3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODM1NzYsImV4cCI6MjA2MTY1OTU3Nn0.YPcdyKJqBs46rtdEPqGfYWvSegK6dL3i3onbA8LA9Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});